### ISSUE TITLE
fix(ts): react-spa-webpack template TS typecheck broken on main — missing @/shared/utils/log-emitter

### ISSUE THREAD

**Issue by guilhermegor** [guilhermegor/blueprintx#452]
## What

`main` is red on the (non-required) **TypeScript typecheck — react-spa-webpack template** check,
since PR #441 ("feat(ts): a LogEmitter port for ts-common + ts-lib/react-spa") landed
(commit `e5c032a`, confirmed still failing at `d57ae19`):

```
src/capabilities/example/context.tsx(3,33): error TS2307: Cannot find module
'@/shared/utils/log-emitter' or its corresponding type declarations.
```

`templates/react-spa-webpack/src/capabilities/example/context.tsx` imports
`CONSOLE_EMITTER` from `@/shared/utils/log-emitter`, but the template-root typecheck job
(which runs `tsc` over `templates/react-spa-webpack/` directly, not a scaffolded project)
has no file at that path — `templates/ts-common/src/utils/log-emitter.ts` is the shared
source, copied into a scaffolded project's `src/shared/utils/` only at scaffold time by
`bin/scaffold/ts_react_app.sh`. The template-root check needs either a local stub/symlink
the CI job resolves, or the copy step run before `tsc`, matching however the other
ts-common-sourced files are already handled for this same check.

## How found

Discovered while unblocking PR #317 (fix/multi-intent-argv-283, issue #283) — after
rebasing onto current `main`, this pre-existing, unrelated failure showed up in PR #317's
CI. Confirmed independently on `main` itself via `gh run list --branch main`, so it is not
caused by #317's changes and is out of scope for that PR (Python `multi_pipeline` only).

## Impact

Not a required branch-protection check today, so it does not block merges — but it leaves
`main` permanently red on this signal until fixed, and mirrors an issue the tests catch (the
template ships a broken import) instead of the tests catching it before merge.

**Comment by guilhermegor** [comment]
Already satisfied on `main` — closing with evidence rather than opening a no-op PR.

Fixed by **#450** (merged 2026-09-11T22:54:24Z), which assembled `ts-common/src` into
the typecheck workspace's `src/shared/`:

```
$ git show origin/main:templates/ts-common/src/utils/log-emitter.ts   # exists
$ git show origin/main:.github/workflows/scaffold_checks.yml | grep -n 'ts-common/src'
477:          cp -r templates/ts-common/src/. /tmp/ts-typecheck/src/shared
```

And the check that was failing is now green on PRs carrying that commit — #450's own
`TypeScript typecheck — react-spa-webpack template` was SUCCESS, while the six PRs
that predated it were red for exactly this reason (#456, #455, #424, #400, #317, #282).
That red was never a defect in those PRs; they simply ran the pre-fix workspace
assembly from their own checkout.

Reopen if the typecheck fails again on a PR whose base includes `9f08841`.
